In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
input = np.array([[7, 6, 4, 2, 1],
[1, 2, 7, 8, 9],
[9, 7, 6, 2, 1],
[1, 3, 2, 4, 5],
[8, 6, 4, 4, 1],
[1, 3, 6, 7, 9]])

In [34]:
with open('input.txt') as f:
    lines = f.readlines()

array_of_lines = [np.array(list(map(int, line.split()))) for line in lines]
input = np.array(array_of_lines, dtype=object)

In [35]:
input

array([array([65, 67, 70, 72, 74, 73]), array([32, 35, 37, 39, 39]),
       array([28, 31, 34, 35, 38, 39, 43]),
       array([51, 54, 56, 58, 59, 60, 63, 70]),
       array([77, 78, 80, 81, 80, 82]), array([28, 31, 32, 35, 32, 31]),
       array([41, 43, 42, 44, 45, 45]),
       array([41, 42, 39, 41, 42, 44, 48]),
       array([14, 15, 13, 14, 17, 20, 21, 26]),
       array([24, 25, 27, 27, 28, 29, 31, 32]),
       array([36, 39, 41, 42, 43, 43, 45, 44]),
       array([80, 82, 84, 84, 84]), array([74, 75, 78, 78, 80, 84]),
       array([12, 14, 14, 17, 20, 26]),
       array([40, 41, 42, 43, 44, 48, 51, 52]),
       array([68, 70, 72, 73, 77, 79, 82, 79]),
       array([70, 71, 75, 77, 80, 80]), array([ 7, 10, 14, 17, 20, 24]),
       array([26, 29, 33, 34, 36, 38, 41, 47]),
       array([15, 16, 23, 25, 26, 28, 29]),
       array([85, 88, 93, 94, 97, 99, 97]),
       array([33, 34, 39, 42, 44, 46, 47, 47]),
       array([77, 79, 86, 88, 91, 92, 94, 98]),
       array([24, 26, 28, 34

In [36]:
safe_count = 0

for report in input:
    # report = input[5]
    # print('report:', report)

    increasing = None
    unsafe = None

    if len(report) < 2:
        unsafe = True
        # print('1')
    else:

        for idx in range(len(report)-1):        
            if unsafe:
                break
            
            if (increasing==None):
                if (report[idx+1] > report[idx]):
                    # print('increasing')
                    increasing = True
                elif (report[idx+1] < report[idx]):
                    # print('decreasing')
                    increasing = False
                else: unsafe = True
            
            if increasing:
                if (report[idx+1] - report[idx]) > 3:
                    unsafe = True
                    # print('> 3')
                if (report[idx+1] <= report[idx]):
                    # print('<=')
                    unsafe = True

            else:
                if (report[idx] - report[idx+1]) > 3:
                    unsafe = True
                    # print('< 3')
                if (report[idx+1] >= report[idx]):
                    unsafe = True
                    # print('>=')
            
        if not unsafe:
            safe_count += 1

print('safe_count', safe_count)

        


safe_count 218
